- Makefile
default proxy-body-size limit the blob upload size
> remove proxy-body-size limit from nginx-ingress

- .github/workflows/tests.yml
Use release url instead of githubusercontent
> fix(ci) New way to deploy CertManager CRDs

- controllers/harbor/components/registry/ingresses.go
add annotation to unlimit the size of http request body.
CLOSES #63
> fix(ingress): resolve 413(Too Large Entity) error when push large image.

- config/default/kustomization.yaml
add default namespace `harbor-operator` in `config/default/kustomization.yaml`
close #136
> fix(crd) add default namespace in kustomization.yaml

- pkg/cluster/controllers/cache/redis.go
- pkg/cluster/controllers/database/postgresql.go
- pkg/cluster/controllers/storage/minio.go
- pkg/cluster/lcm/health.go
- pkg/cluster/lcm/lcm.go
- add health checker interface
- add new checker get method in the lcm controller interface
fix #212
> feat(services): add health checker interface

- Makefile
- avoid cert-manager deploymemt conflicts
- add new target run-with-cm to support install cert-manager before calling run
fix #216
> fix(Makefile):remove certmanager from target run

- controllers/goharbor/harbor/notarysigner.go
close #193 
the default alias key for notary signer should be upper case
reference https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/cmd/notary-signer/config.go#L88
> fix(notary) signer alias key should use upper case envrionment

- controllers/goharbor/core/deployments.go
close #246
trivy can't pull image with auth fail because it is not using internal auth url, because core_url doesn't have port
> fix(trivy) failed pull image

- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/annotations.yaml
- use released versions of the related kus yamls for dependent services(redis,psql and minio)
- also include the images
- redis: v1.0.0
- psql: v1.5.0
- minio: v3.0.13
fix #261
> feat(kustomize):use released versions of kus yamls

- apis/goharbor.io/v1alpha2/harbor_types.go
close #318 
chartPersistentVolume should be optional when not install chartmuseum
> fix spec.imageChartStorage.filesystem.chartPersistentVolume optional

- controllers/goharbor/harbor/core.go
close #326 
fix harbor-core encrypt key length to 16
> fix encrypt key length to 16

- controllers/goharbor/harbor/core.go
- controllers/goharbor/harbor/notarysigner.go
- pkg/controller/resource.go
Update `AddSecretToManage` method to support both mutable and immutable
secret, and remove `AddImmutableSecretToManage` method.
> refactor(controller): one method to add mutable and immutable secret

- controllers/goharbor/core/deployments.go
- pkg/cluster/controllers/database/api/postgresql_type.go
- pkg/cluster/controllers/database/generate.go
- pkg/cluster/controllers/database/utils.go
1. Set the max_connections to 1024 for the incluster postgres database.
2. Limit max_open_conns and max_idle_conns for the core component.
Closes #382
> feat(database): add max_connections for the incluster postgres

- .github/kind.yaml
- .github/workflows/tests.yml
- controllers/goharbor/harbor/harbor_suite_test.go
- controllers/goharbor/harbor/harbor_test.go
- controllers/goharbor/harbor/manifests/trivy/default-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/default.yaml
- controllers/goharbor/harbor/manifests/trivy/expose-core-with-tls-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/expose-core-with-tls.yaml
- controllers/goharbor/harbor/manifests/trivy/github-token-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/github-token.yaml
- controllers/goharbor/harbor/trivy.go
- controllers/goharbor/harbor/trivy_test.go
- manifests/cluster/patch/github-token.yaml
- pkg/controller/resource.go
1. Inject the github token to the trivy spec when the github token ref
is empty in the spec but github token exists in the operator.
2. Patch the GITHUB_TOKEN from the github actions to the operator in CI.
3. Use helm/kind-action to create k8s cluster.
> fix: inject github token from operator to trivy spec

- pkg/image/image.go
- pkg/image/image_test.go
Fix the GetImage function for cluster redis component
> fix: correct GetImage when the respository is empty

- Dockerfile
- charts/harbor-operator/README.md
- charts/harbor-operator/templates/deployment.yaml
- charts/harbor-operator/values.yaml
- config/helm/deployment/patch_deployment_security.yaml
- config/manager/manager.yaml
- manifests/cluster/deployment.yaml
See https://github.com/kubernetes-sigs/kubebuilder/pull/1635 for more
info
> fix: specify nonroot uid for manager

- controllers/goharbor/chartmuseum/deployments.go
- controllers/goharbor/core/deployments.go
- controllers/goharbor/jobservice/deployments.go
- controllers/goharbor/notaryserver/deployments.go
- controllers/goharbor/notarysigner/deployments.go
- controllers/goharbor/portal/deployments.go
- controllers/goharbor/registry/deployments.go
- controllers/goharbor/registryctl/deployments.go
- controllers/goharbor/trivy/deployments.go
- pkg/cluster/controllers/storage/provision.go
Add default security context to harbor and minio components to let
harbor run in the restricted psp enabled k8s.
> feat: add default secuirty context to components

- .github/workflows/tests.yml
- apis/goharbor.io/v1alpha2/harborcluster_types.go
- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/harborcluster/ctrl_setup.go
- controllers/goharbor/harborcluster/harborcluster.go
- manifests/cluster/deployment.yaml
- pkg/builder/builder.go
- pkg/scheme/scheme.go
In the first time harbor operator running, the `postgresql` and `redisfailover` CRDs are not created at the harbor operator manager bootstrap stage, harbor cluster controller will be failed when it owns the postgresql and redisfailover. The controller can't get the notification from the status changing of `postgresql` and `redisfailover`.
This PR will watch the CRD and try to own the objects again after a CRD ready.
> feat: watch the crd and owns object after crd ready

- apis/goharbor.io/v1alpha3/harbor_types.go
Ensure the ImageChartStorage is not nil when validate registryctl.
> fix: correct the validate registryctl

- apis/goharbor.io/v1alpha3/harbor_types_test.go
- apis/goharbor.io/v1alpha3/v1alpha3_suite_test.go
Add tests for ValidateNotary and ValidateRegistryController methods of
HarborSpec
> test: add tests for validate methods of HarborSpec

- apis/goharbor.io/v1alpha3/harborcluster_types.go
- manifests/cluster/deployment.yaml
- pkg/cluster/controllers/cache/resource_manager.go
1. Remove harbor cluster spec redis tlsConfig.
2. Remove set redis keepPVC true as default.
> fix: remove redis tls spec and set keepPVC as false

- pkg/cluster/controllers/storage/tenant.go
> update(storage): update default minio resource limits and requests

- pkg/cluster/controllers/database/readiness.go
Fixes #572
Signed-off-by: Alex Stockinger <mail@alexstockinger.de>
> Make PostgreSQL secrets name template configurable

- config/config/assets/jobservice-config.yaml.tmpl
- controllers/goharbor/chartmuseum/deployments.go
- controllers/goharbor/registry/deployments.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
- handle empty redis password for js
- handle empty redis password for registry
- handle empty redis password for chartmuseum
also fix #608
> fix(config):handle empty redis password

- docs/LCM/backup-minio-data.md
- docs/LCM/backup-psql-data.md
- docs/LCM/backup-redis-data.md
> doc(backup):add notes to the backup docs

- .github/workflows/tests.yml
- README.md
- controllers/goharbor/harbor/notarysigner.go
> fix(ci) support certmanager 1.4

- controllers/goharbor/harbor/ingresses.go
There is a js file named `common.es-2015.xxx.js` in the portal of the
harbor 2.3.0, the request of this file will be transported to the core
component when there isn't a slash at the end of the ingress path,
the portal will not be accessible. So we need to append a slash to the end
of the ingress path.
> fix: append slash to the end of ingress path

- README.md
- docs/installation/customize-storage-db-redis.md
> doc(README):update README to reflect latest changes

- charts/harbor-operator/README.md
- charts/harbor-operator/templates/deployment.yaml
- charts/harbor-operator/values.yaml
- config/helm/deployment/patch_deployment_config.yaml
> add POSTGRES_SECRETS_TEMPLATE in container ENV

- docs/development.md
Hello,
I think we can remove this cert manager command because it causes issues when running the _run_ Makefile target that tries to launch cert-manager too but on a more recent version. I think we should let the _run_ target handle this.
Signed-off-by: Thomas Coudert thomas.coudert@ovhcloud.com
> doc(Development): Remove cert-manager deployment

- controllers/goharbor/harbor/ingresses.go
- controllers/goharbor/notaryserver/services.go
> fix: let backend port in notary ingress depend on internal tls

- controllers/goharbor/harbor/core.go
close #781
we can use `publicDNS.Hostname()` instead of `publicDNS.Host`, in order to remove port from hostname.
Or we just remove this `DNSNames`, using CommonName with any name, because this cert is just to create a key/cert used to encrypt token between notary and core components
> fix core token when using "https://IP:port" as the external URL

- Makefile
- go.mod
- go.sum
Build the controller-gen and stringer in temp dir to avoid the version of harbor pkg always changing in github actions.
> chore: build controller-gen and stringer in temp dir

- controllers/goharbor/registry/deployments.go
Allow for empty S3 SecretKeyRef
Relates to: https://github.com/goharbor/harbor-operator/issues/794
Signed-off-by: Dave Griffiths dave.griffiths@sainsburys.co.uk
> fix: Allow for empty S3 SecretKeyRef

- apis/goharbor.io/v1beta1/harborserverconfiguration_types.go
- charts/harbor-operator/templates/crds.yaml
- docs/configurations/day2-config.md
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
- pkg/rule/rule.go
- pkg/rule/rule_test.go
- webhooks/pod/mutate_image_path.go
Fix readme of day2
ServerURL must begin with http or https
Change rule format
Add unit test
Fix https://github.com/goharbor/harbor-operator/issues/827
> Fix readme of day2

- controllers/goharbor/configuration/cm_reconciler.go
Fixes: https://github.com/goharbor/harbor-operator/issues/826
> fix: adjust the update logic of deprecated configmap day2 configuration

- README.md
- Update the Redis version
- Update the feature list to move some Day2 functions to the future list
- Update the release plans
- remove 1.2
- add 1.4
> doc(README): update for 1.2 GA

- controllers/goharbor/internal/test/postgresql/postgres.go
- controllers/goharbor/internal/test/redis/redis.go
CI "Go tests" is failing, that NotaryServer and NotarySigner pods fail to start
This is because notary binary can't connect to lasted postgres version 14.2 with docker image bitnami/postgresql
So use fixed version for postgres and redis
> use fixed postgresql/redis image in go tests

- controllers/goharbor/registry/deployments.go
This PR backports #811 to the 1.1.x release branch, so that it can be released as a fix.
Here is a working container image: ghcr.io/sagikazarmark/harbor-operator:v1.1.2-custom.1
> [Backport] fix: Allow for empty S3 SecretKeyRef

- controllers/goharbor/chartmuseum/deployments.go
close #838
this is a break change, that minio/aws for chartmuseum folder is changed, you need manually move the charts to folder `chart_storage`
> add prefix folder for chartmuseum

- controllers/goharbor/registry/deployments.go
This PR backports #877 to the 1.2.x release branch.
It's a bugfix, so it should be released as a patch.
> Backport 877 to 1.2.x

- apis/goharbor.io/v1beta1/harbor_types.go
- apis/goharbor.io/v1beta1/trivy_types.go
- charts/harbor-operator/templates/crds.yaml
- controllers/goharbor/harbor/manifests/trivy/default-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/expose-core-with-tls-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/github-token-expected.yaml
- controllers/goharbor/harbor/trivy.go
- controllers/goharbor/trivy/configs.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> [Cherry pick]Support offline scan option in trivy (#909)

- controllers/goharbor/harbor/registryctl.go
- controllers/goharbor/registry/registryctl.go
- controllers/goharbor/registry/resources.go
- pkg/controller/resource.go
> fix: Ignore the status check for the registryctl cr in harbor controller

- .github/workflows/tests.yml
- manifests/cluster/kustomization.yaml
Because current redis operator CRD too long, use `kubectl apply` executer fail， use `kubectl create` can success.
> The CustomResourceDefinition "redisfailovers.databases.spotahome.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
ci: https://github.com/goharbor/harbor-operator/runs/8192620687?check_suite_focus=true
Signed-off-by: rongfu.leng <1275177125@qq.com>
> Too long: must have at most 262144 bytes

- .github/auto-assignees.yaml
- .github/workflows/auto-assign-prs.yaml
Signed-off-by: Marcel Mueller <marcel.mueller1@rwth-aachen.de>
> Add github action to assign maintainers to PRs

- go.mod
- go.sum
See https://github.com/prometheus/client_golang/releases/tag/v1.11.1 for more information
> Update prometheus/client_golang to fix CVE-2022-21698

- config/config/assets/jobservice-config.yaml.tmpl
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
Until now, when setting a custom value for `spec.jobservice.workerCount` in the `HarborCluster` CustomResource, the change is not reflected in the managed harbor instance. This is because the corresponding key in the jobservice's config file (see https://github.com/goharbor/harbor-helm/blob/master/templates/jobservice/jobservice-cm.yaml#L18)  doesn't get set by the operator.
This PR fixes this by setting the value for `worker_pool.workers` in  `config/config/assets/jobservice-config.yaml.tmpl`.
> fix: set jobservice workercount in configmap

- controllers/goharbor/core/deployments.go
The github-cr was missing from the options therefore it was added.
> Add the missing github-cr proxy cache module

- controllers/goharbor/core/secrets.go
- controllers/goharbor/exporter/deployments.go
fix: https://github.com/goharbor/harbor-operator/issues/1054
```
ubuntu@miner:~$ kubectl get secret harborcluster-sample-harbor-harbor-core -n test -o yaml | grep REDIS
_REDIS_URL_CORE: cmVkaXM6Ly86T2RMNTFGVnpUaCU0MFIlMjUlNUUlNDBAMTAuMTg2LjU1LjM1OjYzNzkvMD9pZGxlX3RpbWVvdXRfc2Vjb25kcz0zMA==
_REDIS_URL_REG: cmVkaXM6Ly86T2RMNTFGVnpUaCU0MFIlMjUlNUUlNDBAMTAuMTg2LjU1LjM1OjYzNzkvMT9pZGxlX3RpbWVvdXRfc2Vjb25kcz0zMA==
kubectl get deployment.apps/harborcluster-sample-harbor-harbor-exporter -n test -o yaml
...
- name: HARBOR_REDIS_URL
value: redis://:OdL51FVzTh%40R%25%5E%40@10.186.55.35:6379/2
ubuntu@miner:~$ kubectl get secret harborcluster-sample-harbor-harbor-trivy -n test -o yaml | grep REDIS
SCANNER_JOB_QUEUE_REDIS_URL: cmVkaXM6Ly86T2RMNTFGVnpUaCU0MFIlMjUlNUUlNDBAMTAuMTg2LjU1LjM1OjYzNzkvNQ== …
```
> Allow redis password contains special characters

- charts/harbor-operator/README.md
- charts/harbor-operator/values.yaml
- docs/tutorial.md
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/harbor/deployment.yaml
- manifests/harbor/kustomization.yaml
bases on https://github.com/goharbor/harbor-operator/pull/996, it has to update tag name to dev, rather than dev_master
> update image tag

- docs/day2/day2-harborprojects.md
This pull request adds the HarborProject examples shared [here](https://github.com/goharbor/harbor-operator/pull/1031#issuecomment-1567867031) to the corresponding doc.
> Add examples to harbor project docs
