goharbor/harbor-operator

- config/samples/goharbor_v1alpha1_harbor.yaml
- config/samples/kustomization.yaml
> fix(sample): update the sample yaml to align with latest spec

- api/v1alpha1/harbor_webhook.go
Signed-off-by: Jérémie MONSINJON <jeremie.monsinjon@gmail.com>
fix #2
> Modify mutating webhook path to be compliant with group name

- config/samples/kustomization.yaml
Signed-off-by: Jérémie MONSINJON <jeremie.monsinjon@gmail.com>
> Modify sample crd file extension in kustomize configuration

- Makefile
- config/manager/manager.yaml
> change the default controller image name

- Makefile
fix make install-dependencies error
> fix make install-dependencies

- .github/workflows/lint.yml
- .hadolint.yaml
- docs/installation.md
for #4
add some installation notes for KIND k8s.
please help review how to organize such notes.
> feat(doc) add some installation notes

- Makefile
- config/samples/requirements.tmpl
- docs/install-with-kind-k8s.md
- docs/installation/database-installation.md
- docs/installation/installation.md
- docs/installation/redis-installation.md
- docs/installation/registry-storage-configuration.md
Step by step explanation to deploy postgresql databases in kubernetes with Helm
and the bitnami chart.
> docs(installation) Databases installation in kubernetes. Fix #41.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/issue.md
- .github/ISSUE_TEMPLATE/proposal.md
- README.md
> chore(issues):add github issue templates

- .github/workflows/release.yml
> fix(cd) Use only version part from ${{ github.ref }} as docker tag

- Makefile
- docs/installation/installation.md
Here are some minor fixes for documentation. 
However one is also affecting the Makefile, so please make sure it does not break your dev setups.
Signed-off-by: Jiří Suchomel <jiri.suchomel@suse.com>
> Some documentation fixes

- api/v1alpha1/harbor_types.go
- assets/templates/registry/config.yaml
- controllers/harbor/components/registry/deployments.go
Signed-off-by: xiaoyang zhu <zhuxiaoyang1996@gmail.com>
fix #63
> redirect: disable: false` should be exposed at the harbor CR spec

- api/v1alpha1/harbor_secret_format.go
- api/v1alpha1/harbor_types.go
- config/manager/manager.yaml
- controllers/harbor/components/harbor-core/deployments.go
- main.go
Fix missing `_REDIS_URL` env of harbror-core
Fixes #76
> fix(core): fix missing `_REDIS_URL` env of harbror-core

- config/manager/kustomization.yaml
- controllers/harbor/components/harbor-core/deployments.go
> fix(bug): fix core wrong cacheSecret

- docs/installation/database-installation.md
- docs/installation/redis-installation.md
This PR specifies the secret type when creating with kubectl during installation.
Signed-off-by: Simon Weald <glitchcrab-github@simonweald.com>
> Minor documentation corrections

- .github/workflows/tests.yml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
> fix(deploy) fix kustomize controller image

- apis/goharbor.io/v1alpha2/chartmuseum_types.go
- apis/goharbor.io/v1alpha2/harbor_types.go
- config/samples/registry/goharbor_v1alpha2_registry.yaml
- controllers/goharbor/chartmuseum/deployments.go
- controllers/goharbor/harbor/chartmuseum.go
> feat(apis) Expose ChartMuseum absolute url in Harbor CRD

- controllers/harbor/health.go
refactor GetHealth method, using in-cluster service to get health.
CLOSE #112
> fix(status): fix ready condition in status.

- controllers/harbor/components/chartmuseum/ingresses.go
- controllers/harbor/components/harbor-core/ingresses.go
- controllers/harbor/components/notary/ingresses.go
- controllers/harbor/components/portal/ingresses.go
- pkg/ingress/ingress.go
> fix(cert):roll back ingress cert changes

- controllers/harbor/components/harbor-core/configs.go
- controllers/harbor/components/harbor-core/deployments.go
cherry-pick from https://github.com/goharbor/harbor-operator/pull/89
> fix: replace subpath mount by folder mount to use secret synchronization

- charts/harbor-operator/templates/service.yaml
> fix(chart) Update service target port to match port of the pod

- Makefile
> fix(makefile) Remove useless GITHUB_USER variable

- Makefile
> feat(ci) fix helm-install target

- .github/workflows/build-dev.yml
- .github/workflows/tests.yml
- config/helm/webhook/kustomization.yaml
fix #134 
helm webhook cert is not correctly injected
> Fix helm webhook cert

- controllers/goharbor/harbor/core.go
fix #138 
admin password set in config/samples/harbor/kustomization.yaml:22 is not pass to harbor core
> fix(core) admin password wrong

- charts/harbor-operator/Chart.yaml
close #133
Fix chart ingress enable value not working
> Fix chart ingress enable

- .github/workflows/tests.yml
- charts/harbor-operator/values.yaml
add ci cases
1. install harbor-operator
2. install harbor
3. curl api
4. docker push
microk8s 1.17 doesn't support registry with ipv6
> enhance CI testing

- .github/workflows/tests.yml
- charts/harbor-operator/Chart.lock
- charts/harbor-operator/README.md
- charts/harbor-operator/templates/deployment.yaml
- charts/harbor-operator/templates/validatingwebhookconfiguration.yaml
fix(ci) sync charts files
close #145
run `make generated-diff-test` and commit files
> fix(ci) sync charts files

- Makefile
Signed-off-by: Simon Guyennet <simon.guyennet@corp.ovh.com>
> fix(makefile) kustomize install

- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/trivy/trivy.go
close #175 
fix trivy permission issue
> fix(trivy) permission failed

- controllers/goharbor/harborcluster/database/postgresql.go
- controllers/goharbor/harborcluster/harborcluster_controller.go
- pkg/k8s/option.go
upport ctrl options for lcm controllers
> feat(options) support ctrl options for lcm controllers

- apis/goharbor.io/v1alpha2/harborcluster_types.go
remove version from HarborCluster spec
CLOSE #196
> feat(harborcluster): remove version

- config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
- pkg/cluster/cache/redis.go
- pkg/cluster/database/postgresql.go
- pkg/cluster/harbor/harbor.go
- pkg/cluster/storage/delete.go
- pkg/cluster/storage/minio.go
- pkg/cluster/storage/upgrade.go
- pkg/lcm/lcm.go
- vendor/modules.txt
Fix: https://github.com/goharbor/harbor-operator/issues/200
> fix: adjust lcm controller interface, first params use ctx

- config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
- pkg/cluster/controllers/cache/readiness.go
- pkg/cluster/controllers/cache/redis.go
- pkg/cluster/controllers/cache/resource_manager.go
Fix: https://github.com/goharbor/harbor-operator/issues/204
> fix(redis-controller): fix npe issue and some logic error

- main.go
- pkg/setup/setup.go
- fix typo func name `WabhooksWithManager()`
fix #223
> refactor(main): refactor main.go to reduce duplicate code

- .github/workflows/codeql-analysis.yml
add the related workflow configuration file
> enable github security scan

- pkg/cluster/controllers/storage/minio.go
- pkg/cluster/controllers/storage/provision.go
> fix(storage):add prefix for minio related resource

- pkg/cluster/controllers/database/healthchecker.go
- pkg/cluster/controllers/database/postgresql.go
add healthchecker for postgresql controller
> feat(database) add healthchecker for postgresql controller

- controllers/goharbor/harbor/core.go
close #243
notary is not shown on UI
> Fix notary not shown on UI

- controllers/goharbor/harborcluster/ctrl_setup.go
- pkg/cluster/controllers/cache/redis.go
- pkg/cluster/controllers/cache/resource_manager.go
- pkg/cluster/controllers/database/postgresql.go
- pkg/cluster/controllers/harbor/harbor.go
- pkg/cluster/controllers/storage/minio.go
> fix(controller):use context from cluster reconciler

- pkg/cluster/controllers/cache/resource_manager.go
Fix: https://github.com/goharbor/harbor-operator/issues/255
> fix(lcm): fix redis controller service labels

- pkg/cluster/controllers/storage/client.go
- pkg/cluster/controllers/storage/minio.go
- remove all the log.Fatal()
- add context as 1st param to the minio interface
fix #258,close #258
> fix(minio):fix operator exit issue

- pkg/setup/setup.go
- remove errorgroup in the `WebhooksWithManager` func
fix #202
> fix(webhook):register webhook in single thread

- pkg/cluster/controllers/database/readiness.go
psql service health check failed
fix #256
> fix(database) psql service health check failed

- controllers/goharbor/registry/deployments.go
> fix(registry) Add secret key field to deployment env var for storage driver

- pkg/cluster/controllers/harbor/harbor.go
close #269
fix error: "reconcile harbor service error: expected pointer, but got nil"
> fix(controller) apply harborcluster fail

- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/harborcluster/ctrl_setup.go
- manifests/cluster/deployment.yaml
- add write permissions of harbors to harborcluster ctrl
fix #273
> fix(rbac):update rbac settings of harborcluster ctrl

- apis/goharbor.io/v1alpha2/harbor_types.go
- apis/goharbor.io/v1alpha2/zz_generated.deepcopy.go
- controllers/goharbor/harbor_test.go
- pkg/cluster/controllers/harbor/harbor.go
> fix(ctrl):update harbor ctrl to fix #275

- manifests/samples/full_stack.yaml
> fix cluster sample yaml

- pkg/cluster/controllers/database/generate.go
- pkg/cluster/controllers/database/postgresql.go
- pkg/cluster/controllers/database/provision.go
- pkg/cluster/controllers/database/readiness.go
- pkg/cluster/controllers/harbor/harbor.go
- pkg/cluster/controllers/storage/provision.go
> Fix/issue #289 inconsistent psql name

- pkg/cluster/controllers/storage/provision.go
> fix(minio): fix minio resource name

- config/samples/database/kustomization.yaml
- config/samples/redis/kustomization.yaml
> fix(sample) Specify sample secret type

- manifests/samples/full_stack.yaml
close https://github.com/goharbor/harbor-cluster-operator/issues/235
some setting is not correct in sample full_stack.yaml
> fix full_stack.yaml

- controllers/goharbor/harborcluster/service_mgr.go
- controllers/goharbor/harborcluster/svc_config.go
implement svc config getter
fix #297
> feat(database) implement svc config getter

- pkg/cluster/controllers/database/readiness.go
close #306 
database user is not correct
> fix database user

- controllers/goharbor/harborcluster/svc_config.go
Close:  https://github.com/goharbor/harbor-operator/issues/301
> feat: add redis svcConfigGetter

- pkg/cluster/controllers/storage/minio.go
close #305
fix registry s3 secret
> fix registry s3 secret

- pkg/cluster/controllers/storage/healthchecker.go
- pkg/cluster/controllers/storage/minio.go
> fix(minio):add an empty healthchecker for storage

- Makefile
> feat(make): add phony target to dist/harbor-operator_linux_amd64/manager

- controllers/goharbor/harbor/jobservice.go
close #327 
fix coreurl mismatch, lost port
> fix coreurl mismatch

- controllers/goharbor/chartmuseum/chartmuseum.go
- controllers/goharbor/core/core.go
- controllers/goharbor/jobservice/jobservice.go
- controllers/goharbor/notaryserver/notaryserver.go
- controllers/goharbor/notarysigner/notarysigner.go
- controllers/goharbor/portal/portal.go
- controllers/goharbor/registry/registry.go
- controllers/goharbor/registryctl/registryctl.go
- controllers/goharbor/trivy/trivy.go
- pkg/config/config.go
> update harbor version to 2.1.2

- .github/workflows/tests.yml
- manifests/samples/full_stack_fs.yaml
change CI to use harborcluster
> fix ci for cluster-operator

- controllers/goharbor/harborcluster/status.go
> fix(ctrl):update cluster ctrl for status timestamp

- controllers/goharbor/harborcluster/svc_config.go
handle health checking of filesystem storage driver
fix #333
> fix(minio):update svcconfig getter

- manifests/samples/full_stack.yaml
- manifests/samples/full_stack_fs.yaml
- pkg/cluster/controllers/cache/resource_manager.go
- pkg/cluster/controllers/cache/utils.go
- pkg/cluster/controllers/database/api/postgresql_type.go
- pkg/cluster/controllers/database/generate.go
- pkg/cluster/controllers/database/utils.go
Fix: https://github.com/goharbor/harbor-operator/issues/330
> fix: cache and database use specify storageclass

- pkg/cluster/controllers/storage/provision.go
Fix：https://github.com/goharbor/harbor-operator/issues/338
> fix: fix generated minio ingress rules backend service name

- pkg/cluster/controllers/storage/provision.go
> fix: fix the s3 configuration when redirect disable is false

- controllers/goharbor/harborcluster/ctrl_setup.go
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/images.yaml
- manifests/commons/kustomization.yaml
- manifests/commons/patches-images.yaml
- manifests/harbor/deployment.yaml
- manifests/harbor/kustomization.yaml
- manifests/harbor/patch/images.yaml
- pkg/cluster/controllers/cache/image.go
- pkg/cluster/controllers/cache/redis.go
- pkg/cluster/controllers/cache/resource_manager.go
- pkg/cluster/controllers/database/generate.go
- pkg/cluster/controllers/database/image.go
- pkg/cluster/controllers/database/postgresql.go
- pkg/cluster/controllers/storage/image.go
- pkg/cluster/controllers/storage/minio.go
- pkg/cluster/controllers/storage/provision.go
- pkg/k8s/option.go
- add patch to kustomization template to inject env for configStore to identify
- update deployment manifest yamls
Fix #331
> fix(image):allow image customization

- manifests/samples/full_stack.yaml
- pkg/cluster/controllers/storage/provision.go
Fix：https://github.com/goharbor/harbor-operator/issues/343
> fix: fix full stack certs lost minio domain and minio s3 enable v4auth

- controllers/goharbor/harbor/notarysigner.go
close #357 
fix notary signer cert name too long
> fix(notary) cert name too long

- manifests/samples/full_stack_other_fs.yaml
add other dependencies in sample yaml
> add other dependencies in sample yaml

- controllers/goharbor/harbor/ingresses.go
Signed-off-by: Wenkai Yin <yinw@vmware.com>
> Fix NCP ingress issues

- pkg/cluster/controllers/harbor/harbor.go
> feat(harborcluster): update harborcluster cr status

- controllers/goharbor/harborcluster/svc_config.go
- go.mod
- go.sum
- pkg/cluster/controllers/storage/healthchecker.go
- pkg/cluster/lcm/health.go
- vendor/github.com/ncw/swift/.gitignore
- vendor/github.com/ncw/swift/.travis.yml
- vendor/github.com/ncw/swift/COPYING
- vendor/github.com/ncw/swift/README.md
- vendor/github.com/ncw/swift/auth.go
- vendor/github.com/ncw/swift/auth_v3.go
- vendor/github.com/ncw/swift/compatibility_1_0.go
- vendor/github.com/ncw/swift/compatibility_1_1.go
- vendor/github.com/ncw/swift/compatibility_1_6.go
- vendor/github.com/ncw/swift/compatibility_not_1_6.go
- vendor/github.com/ncw/swift/dlo.go
- vendor/github.com/ncw/swift/doc.go
- vendor/github.com/ncw/swift/go.mod
- vendor/github.com/ncw/swift/largeobjects.go
- vendor/github.com/ncw/swift/meta.go
- vendor/github.com/ncw/swift/notes.txt
- vendor/github.com/ncw/swift/slo.go
- vendor/github.com/ncw/swift/swift.go
- vendor/github.com/ncw/swift/timeout_reader.go
- vendor/github.com/ncw/swift/travis_realserver.sh
- vendor/github.com/ncw/swift/watchdog_reader.go
- vendor/modules.txt
> Implement swift storage health checker

- .github/workflows/tests.yml
update some CI metrix
1. certManager to latest 3 releases
2. update kind and node images
3. fix some timeout problem
> update some CI feature

- controllers/goharbor/harbor/ingresses.go
- pkg/cluster/controllers/common/utils.go
- pkg/cluster/controllers/storage/provision.go
> minio support NCP(NSX) ingress controller

- apis/goharbor.io/v1alpha2/harborcluster_types.go
- config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
- manifests/cluster/deployment.yaml
- manifests/samples/full_stack.yaml
- manifests/samples/full_stack_fs.yaml
- manifests/samples/full_stack_other_fs.yaml
- pkg/cluster/controllers/cache/constants.go
- pkg/cluster/controllers/cache/deploy.go
- pkg/cluster/controllers/cache/readiness.go
- pkg/cluster/controllers/cache/resource_manager.go
remove useless redis service
fix #350
> feat(redis) remove useless redis service

- controllers/goharbor/harbor/harbor_suite_test.go
- controllers/goharbor/harbor/harbor_test.go
- controllers/goharbor/harbor/jobservice.go
- controllers/goharbor/harbor/manifests/jobservice/default-expected.yaml
- controllers/goharbor/harbor/manifests/jobservice/default.yaml
- controllers/goharbor/harbor/manifests/jobservice/repository-and-tag-suffix-not-empty-expected.yaml
- controllers/goharbor/harbor/manifests/jobservice/repository-and-tag-suffix-not-empty.yaml
- controllers/goharbor/harbor/manifests/jobservice/repository-not-empty-expected.yaml
- controllers/goharbor/harbor/manifests/jobservice/repository-not-empty.yaml
- controllers/goharbor/harbor/manifests/jobservice/tag-suffix-not-empty-expected.yaml
- controllers/goharbor/harbor/manifests/jobservice/tag-suffix-not-empty.yaml
- controllers/goharbor/harbor/manifests/jobservice/version-and-repository-not-empty-expected.yaml
- controllers/goharbor/harbor/manifests/jobservice/version-and-repository-not-empty.yaml
- controllers/goharbor/harbor/manifests/jobservice/version-not-empty-expected.yaml
- controllers/goharbor/harbor/manifests/jobservice/version-not-empty.yaml
- manifests/cluster/deployment.yaml
- manifests/cluster/patch/images.yaml
> fix: correct the component spec when get jobservice cr

- controllers/goharbor/harbor/trivy.go
> feat(trivy): make github token optional.

- .github/workflows/tests.yml
- manifests/samples/full_stack_other_fs.yaml
based on #388, we can remove github token in ci
> fix(ci) github token is not must

- controllers/goharbor/harbor/core.go
fix https://github.com/goharbor/harbor-operator/issues/326 for release-0.6.0
> fix encrypt key length to 16

- controllers/goharbor/harbor/jobservice.go
fix https://github.com/goharbor/harbor-operator/issues/327 for 0.6.0
> fix coreurl mismatch 0.6.0

- .github/workflows/tests.yml
- manifests/samples/full_stack_other_fs.yaml
> feat(ci) import harbor apidb test

- pkg/cluster/controllers/storage/image.go
> fix: correct get image for minio

- apis/goharbor.io/v1alpha2/harborcluster_types.go
- controllers/goharbor/configuration/reconciler.go
> feat: add harbor configuration condition to harbor cluster status

- .github/workflows/tests.yml
- controllers/goharbor/core/deployments.go
- manifests/samples/full_stack_other_fs.yaml
> feat: add PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE env

- pkg/cluster/controllers/cache/resource_manager.go
Fix: https://github.com/goharbor/harbor-operator/issues/394
> fix(redis): keep redis pvc after harbor cluster delete

- pkg/cluster/controllers/storage/provision.go
> fix(storage): fix nil pointer error

- controllers/goharbor/chartmuseum/chartmuseum.go
- controllers/goharbor/chartmuseum/chartmuseum_test.go
- controllers/goharbor/chartmuseum/suite_test.go
- controllers/goharbor/core/core.go
- controllers/goharbor/harbor/harbor.go
- controllers/goharbor/jobservice/jobservice.go
- controllers/goharbor/notaryserver/notaryserver.go
- controllers/goharbor/notarysigner/notarysigner.go
- controllers/goharbor/portal/portal.go
- controllers/goharbor/registry/registry.go
- controllers/goharbor/registryctl/registryctl.go
- controllers/goharbor/trivy/trivy.go
- pkg/config/config.go
- pkg/controller/helpers.go
- pkg/controller/mutation.go
Signed-off-by: Simon Guyennet <simon.guyennet@corp.ovh.com>
> fix(harbor class) Close #399

- manifests/samples/full_stack.yaml
> feat: update harbor cluster full-stack sample

- apis/goharbor.io/v1alpha2/harborcluster_types.go
- manifests/samples/full_stack.yaml
- pkg/cluster/controllers/storage/minio.go
- pkg/cluster/controllers/storage/provision.go
add required field in the minio spec for specifying secret
> add required field in the minio spec for specifying secret

- pkg/cluster/controllers/storage/provision.go
> fix(storage): fix minio tls 

- pkg/cluster/controllers/storage/provision.go
> fix(storage): fix minio ingress

- controllers/goharbor/harborcluster/service_mgr.go
- pkg/cluster/lcm/lcm.go
> feat(harbocluster): remove health check

- Makefile
> feat(makefile) Hide stderr for $(shell ...) command

- Dockerfile
> chore: revert USER to nonroot:nonroot in Dockerfile

- .github/workflows/tests.yml
- .golangci.yml
- Makefile
- controllers/goharbor/configuration/reconciler.go
- controllers/goharbor/harbor/ingresses.go
- controllers/goharbor/harborcluster/harborcluster.go
- controllers/goharbor/harborcluster/service_mgr.go
- controllers/goharbor/harborcluster/status.go
- controllers/goharbor/harborcluster/svc_config.go
- pkg/cluster/controllers/cache/constants.go
- pkg/cluster/controllers/cache/readiness.go
- pkg/cluster/controllers/cache/redis_connect.go
- pkg/cluster/controllers/cache/resource_manager.go
- pkg/cluster/controllers/common/utils.go
- pkg/cluster/controllers/database/utils.go
- pkg/cluster/controllers/storage/constants.go
- pkg/cluster/controllers/storage/minio.go
- pkg/cluster/controllers/storage/provision.go
- pkg/harbor/client.go
- pkg/status/status.go
enable more golint check for CI, except `goerr113`
> Enable ci golint

- controllers/goharbor/trivy/deployments.go
> fix: apply component spec to trvy deployment

- pkg/cluster/controllers/storage/provision.go
> fix s3 secret endpoint generate

- controllers/goharbor/core/deployments.go
fix comment in pr https://github.com/goharbor/harbor-operator/pull/126
> fix const DefaultAllowedRegistryTypesForProxyCache

- pkg/cluster/controllers/database/readiness.go
remove pg status check
fix #474
> fix(pg) remove pg status check

- apis/goharbor.io/v1alpha2/harbor_types.go
- apis/goharbor.io/v1alpha2/harbor_webhook.go
- apis/goharbor.io/v1alpha2/harborcluster_webhook.go
- manifests/cluster/deployment.yaml
> fix: validate notary ingress when it's enabled

- .github/workflows/tests.yml
- charts/harbor-operator/templates/mutatingwebhookconfiguration.yaml
- config/helm/webhook/mutatingwebhook_endpoint_patch.yaml
- config/kustomizeconfig/harborcluster.yaml
- config/kustomizeconfig/kustomization.yaml
- config/samples/harborcluster/goharbor_v1alpha2_harborcluster.yaml
- config/samples/harborcluster/https.yaml
- config/samples/harborcluster/kustomization.yaml
- config/samples/harborcluster/service_token_issuer.yaml
- config/samples/harborcluster/storage.yaml
add chart for harborcluster, add chart CI again
> add chart for harborcluster

- pkg/controller/errors.go
Do manual retry without error when an optimistic lock error found. For
more info, see https://github.com/kubernetes/kubernetes/issues/28149
Closes #493
> fix: requeue request when optimistic lock error found

- pkg/controller/mutation.go
- pkg/controller/resource.go
1. Add immutable annotation to the resource when it's immutable.
2. Mark the resource as unchanged when immutable annotation found to
skip the update action for it.
3. Add immutable annotation to the secret resource when it's immutable.
Closes #494
> fix: mark resource as unchanged when it's immutable

- manifests/cluster/deployment.yaml
> fix: correct the image in the cluster deployment.yaml

- apis/goharbor.io/v1alpha2/harbor_types.go
- apis/goharbor.io/v1alpha2/harbor_webhook.go
- apis/goharbor.io/v1alpha2/harborcluster_webhook.go
- apis/goharbor.io/v1alpha2/zz_generated.deepcopy.go
- controllers/goharbor/harbor/chartmuseum.go
- controllers/goharbor/harbor/core.go
- controllers/goharbor/harbor/harbor.go
- controllers/goharbor/harbor/jobservice.go
- controllers/goharbor/harbor/notaryserver.go
- controllers/goharbor/harbor/notarysigner.go
- controllers/goharbor/harbor/portal.go
- controllers/goharbor/harbor/registry.go
- controllers/goharbor/harbor/registryctl.go
- controllers/goharbor/harbor/trivy.go
- manifests/cluster/deployment.yaml
> feat: add RegistryController to components of harbor

- pkg/controller/errors.go
> feat(log) Display error string when error is handled

- README.md
> doc(README): add status badges

- pkg/cluster/controllers/cache/resource_manager.go
> fix: fix incluster redis resources limit not work

- pkg/cluster/controllers/database/readiness.go
Psql credential secret NOT FOUND error
> fix(pg) Psql credential secret NOT FOUND error

- pkg/cluster/controllers/database/readiness.go
The core and notary pods cannot start up when reinstall the Harbor
instance
fix #528
> fix(database) the core and notary pods cannot start up

- controllers/goharbor/chartmuseum/services.go
- controllers/goharbor/jobservice/services.go
- controllers/goharbor/portal/services.go
- controllers/goharbor/registryctl/services.go
- controllers/goharbor/trivy/services.go
> fix: only expose needed ports in service of components

- apis/goharbor.io/v1alpha3/harborcluster_types.go
- controllers/goharbor/harborcluster/status.go
- manifests/cluster/deployment.yaml
> fix(harborcluster): improve the get -o printing columns

- Makefile
- config/config/config.yaml
- config/config/kustomization.yaml
- config/manager/manager.yaml
- config/manager/patches-configuration.yaml
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
fix #517 
add controller config files for kustomize
> fix kustomize configuration

- manifests/samples/harbor_core_minio.yaml
- manifests/samples/harbor_full_minio.yaml
- pkg/cluster/controllers/storage/tenant.go
> fix: set resources of minio from spec of harbor cluster

- .golangci.yml
- apis/goharbor.io/v1alpha3/harbor_webhook.go
- apis/goharbor.io/v1alpha3/harborcluster_webhook.go
- controllers/goharbor/configuration/reconciler.go
- controllers/goharbor/harborcluster/service_mgr.go
- controllers/goharbor/harborcluster/status.go
- pkg/builder/builder.go
- pkg/cluster/controllers/cache/redis.go
- pkg/cluster/controllers/database/readiness.go
- pkg/cluster/controllers/database/utils.go
- pkg/cluster/gos/group.go
- pkg/config/errors_test.go
- pkg/harbor/configuration.go
- pkg/image/image.go
- pkg/image/image_test.go
- pkg/version/version.go
> fix golanglint goerr113

- controllers/goharbor/harbor/ingresses.go
close #570 
fix(ingress) ncp portal path
> fix(ingress) ncp portal path

- .github/workflows/build-dev.yml
- .github/workflows/release.yml
- Makefile
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/harbor/deployment.yaml
- manifests/harbor/kustomization.yaml
change default image registry to ghcr.io which caches all images used
> feat(ci) change image registry

- README.md
- docs/LCM/backup-data.md
- docs/LCM/backup-minio-data.md
- docs/LCM/backup-psql-data.md
- docs/LCM/backup-redis-data.md
- docs/LCM/cluster-controller.md
- docs/LCM/cluster-deletion.md
- docs/LCM/controllers.md
- docs/LCM/monitor-logs-with-grafana.md
- docs/LCM/upgrade-cluster.md
- docs/arch/arch.md
- docs/makefile.md
- docs/manifests-reference.md
- docs/tutorial.md
- manifests/samples/harborcluster_standard_stack_external.yaml
- complete tutorial
- complete cluster deletion
- add doc placeholders for backup data
- add doc placeholder for upgrade cluster
- add doc placeholder for monitor logs
- add one more sample manifest for deploying full harbor with all external services
> doc(tutorial): draft tutorial doc

- pkg/cluster/controllers/database/utils.go
> fix: correct the resource limits for the postgres

- pkg/harbor/configuration.go
Fix：https://github.com/goharbor/harbor-operator/issues/568
> fix: set http header when put harbor configuration

- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/annotations.yaml
- manifests/cluster/patch/delete-duplicated-ns.yaml
- manifests/cluster/patch/delete-minio-console.yaml
> fix(kustomization):rm minio console deployment

- docs/LCM/backup-redis-data.md
Close: https://github.com/goharbor/harbor-operator/issues/566
> docs: add in-cluster redis backup document

- docs/configurations/day2-config.md
Close: https://github.com/goharbor/harbor-operator/issues/562
> docs: add day2 configuration document

- docs/configurations/resource-configurations.md
> docs: add resource-configurations.md

- apis/goharbor.io/v1alpha3/harborcluster_webhook.go
> fix(webhook):revise in-cluster storage webhook

- controllers/goharbor/registryctl/resources.go
- pkg/controller/resource.go
> fix: make registryctl depend on config of registry

- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/pg-configmap.yaml
add pg default resource config
fix #539
> fix(pg) add pg default resource config

- apis/goharbor.io/v1alpha3/harborcluster_types.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
- pkg/cluster/controllers/database/utils.go
add postgress kb annotation and comments
fixed #552
> fix(pg) add postgress kb annotation and comments

- docs/LCM/upgrade-cluster.md
> docs: add doc about upgrade harbor cluster

- README.md
- docs/installation/customize-storage-db-redis.md
- docs/tutorial.md
- add storage, db and cache customization doc in the README
also fix #615
> doc(installation):add doc for custimizing storage,db and cache

- manifests/samples/standard_stack.yaml
> fix(samples):revise errors in sample manifest

- apis/goharbor.io/v1alpha3/registry_types.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> fix: remove the scale subresource for registry resource

- docs/perf/simple-perf-comprasion.md
> docs: add doc of perf

- pkg/cluster/controllers/storage/job.go
> feat: set ttlSecondsAfterFinished for job of init bucket

- docs/LCM/backup-psql-data.md
> doc(pg) add postgres backup doc

- docs/LCM/backup-minio-data.md
> feature(doc): backup minio data

- MAINTAINERS
Signed-off-by: Pierre PÉRONNET <pierre.peronnet@gmail.com>
> feat(maintainers) Update holyhope corp

- controllers/goharbor/harbor/notaryserver.go
fix version.SetVersion()
close #652
> fix(version) notaryserver.go

- controllers/goharbor/harbor/notaryserver.go
fix version.SetVersion()
close #652
> [cherry-pick ]fix(version) notaryserver.go 1.0.1

- .github/workflows/tests.yml
- apis/goharbor.io/v1alpha3/harbor_types.go
- apis/meta/v1alpha1/ingress_controller.go
- controllers/goharbor/core/services.go
- controllers/goharbor/harbor/core.go
- controllers/goharbor/harbor/ingresses.go
- controllers/goharbor/harbor/notaryserver.go
- controllers/goharbor/harbor/portal.go
- controllers/goharbor/notaryserver/services.go
- controllers/goharbor/portal/services.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
- manifests/samples/full_stack.yaml
- manifests/samples/minimal_stack_fs.yaml
- manifests/samples/minimal_stack_incluster.yaml
- manifests/samples/standard_stack.yaml
- manifests/samples/standard_stack_fs.yaml
- pkg/cluster/controllers/common/utils.go
- pkg/cluster/controllers/storage/ingress.go
> add contour support

- .github/workflows/tests.yml
- apis/goharbor.io/v1alpha3/harbor_types.go
- apis/meta/v1alpha1/ingress_controller.go
- controllers/goharbor/core/services.go
- controllers/goharbor/harbor/core.go
- controllers/goharbor/harbor/ingresses.go
- controllers/goharbor/harbor/notaryserver.go
- controllers/goharbor/harbor/portal.go
- controllers/goharbor/notaryserver/services.go
- controllers/goharbor/portal/services.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
- manifests/samples/full_stack.yaml
- manifests/samples/minimal_stack_fs.yaml
- manifests/samples/minimal_stack_incluster.yaml
- manifests/samples/standard_stack.yaml
- manifests/samples/standard_stack_fs.yaml
- pkg/cluster/controllers/common/utils.go
- pkg/cluster/controllers/storage/ingress.go
> [cherry-pick] Add contour support 1.0.1

- charts/harbor-operator/Chart.yaml
Signed-off-by: Pierre PÉRONNET <pierre.peronnet@gmail.com>
> feat(helm) Add support for kubernetes prerelease version. Fix #453

- pkg/cluster/controllers/database/readiness.go
> fix(database) set ref pg secret owner

- pkg/cluster/controllers/database/readiness.go
fixed #660
(cherry picked from commit 055b6b5d248863101467f179f3c3e27b0c6065b4)
> fix(database) set ref pg secret owner (#662)

- charts/harbor-operator/Chart.yaml
Signed-off-by: Pierre PÉRONNET <pierre.peronnet@gmail.com>
> [CHEERY-PICK]feat(helm) Add support for kubernetes prerelease version (#666)

- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/harborcluster/ctrl_setup.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
- pkg/cluster/controllers/storage/minio.go
> feature(storage):clear minio pvc after HarborCluster is deleted

- README.md
- docs/LCM/upgrade-cluster.md
> doc(readme): update versioning and compatibility matrix

- README.md
- docs/LCM/upgrade-cluster.md
> [CHERRY-PICK] doc(readme): update versioning and compatibility matrix (#675)

- Makefile
- config/manager/manager.yaml
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/harbor/deployment.yaml
- manifests/harbor/kustomization.yaml
> update version 1.0.1

- apis/goharbor.io/v1alpha3/harbor_types.go
- controllers/goharbor/harbor/harbor.go
- controllers/goharbor/harbor/ingresses.go
- controllers/goharbor/harbor/jobservice.go
- pkg/cluster/controllers/storage/ingress.go
- pkg/controller/resource.go
- pkg/controller/resource_test.go
> feat(api) upgrade ingress api from v1beta to v1

- pkg/cluster/controllers/storage/job.go
> fix: remove ttl for job of creating bucket

- README.md
- add release plan 1.1
- add release plan 1.2
> doc(Readme): add release plan sections

- .github/workflows/tests.yml
- README.md
> fix k8s version

- apis/goharbor.io/v1alpha3/harbor_types.go
- apis/goharbor.io/v1beta1/harbor_types.go
> fix: add missing component spec copy for exporter

- pkg/cluster/controllers/storage/ingress.go
> fix(nil): ingress nil panic

- .github/workflows/tests.yml
- manifests/samples/minimal_stack_fs_v1beta1.yaml
- manifests/samples/minimal_stack_incluster_v1beta1.yaml
- manifests/samples/standard_stack_fs_v1beta1.yaml
close https://github.com/goharbor/harbor-operator/issues/720
1. add v1beta1 sample
2. change CI to use v1beta1 sample
> add v1beta1 sample

- pkg/image/components.go
> upgrade minio to latest version

- .github/workflows/build-dev.yml
close https://github.com/goharbor/harbor-operator/issues/731
> fix go version in CI charts

- .github/workflows/tests.yml
- pkg/image/image.go
fix minio memory leak issue https://github.com/goharbor/harbor-operator/issues/726
> update minio version

- .github/workflows/tests.yml
- Makefile
- docs/installation/by-helm-chart.md
- docs/installation/kustomization-all-in-one.md
update some tools minor version
> feat(ci) update tools version

- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/configuration/cm_reconciler.go
- controllers/goharbor/harbor/harbor.go
- controllers/goharbor/harborcluster/ctrl_setup.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> fix(openshift): fix issue 698

- apis/goharbor.io/v1beta1/harbor_configuration.go
> fix json unmarshal bug

- Makefile
Add kind tool to enable easier local testing
> feat(dev): add kind tools

- docs/installation/by-helm-chart.md
Signed-off-by: Henry <kangkai-iri@360.cn>
> doc(by-helm-chart):Update Harbor operator by helm chart

- docs/CRD/custom-resource-definition.md
> feat(doc): update harbrcluster crd

- controllers/goharbor/configuration/reconciler.go
> fix(configuration): clean status reason when reconcile success

- docs/installation/by-helm-chart.md
- docs/installation/enable_minio_console.md
- docs/installation/kustomization-all-in-one.md
- docs/installation/kustomization-custom.md
- docs/makefile.md
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/annotations.yaml
- manifests/harbor/deployment.yaml
- manifests/harbor/kustomization.yaml
> feat(release) update version in docs

- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/configuration/cm_reconciler.go
- controllers/goharbor/harbor/harbor.go
- controllers/goharbor/harborcluster/ctrl_setup.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> enhance(rbac): support to openshift

- charts/harbor-operator/templates/clusterrole.yaml
- controllers/goharbor/configuration/cm_reconciler.go
- controllers/goharbor/harbor/harbor.go
- controllers/goharbor/harborcluster/ctrl_setup.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> CherryPick(openshift): add support for openshift

- docs/installation/kustomization-all-in-one.md
- docs/tutorial.md
> doc(tutorial):update the outdated guides info

- docs/installation/enable_minio_console.md
- docs/installation/kustomization-all-in-one.md
- docs/installation/kustomization-custom.md
- docs/tutorial.md
- manifests/cluster/deployment.yaml
reference pr https://github.com/goharbor/harbor-operator/pull/789
fix typo in doc
> feat(doc) update doc typo

- charts/harbor-operator/charts/redisoperator/templates/rbac.yaml
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/redis-rbac.yaml
Fixes: https://github.com/goharbor/harbor-operator/issues/786
> fix: add redis cluster role patch to be compatible with openshift

- .github/kind.yaml
- charts/harbor-operator/Chart.lock
- charts/harbor-operator/Chart.yaml
- go.mod
- go.sum
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/annotations.yaml
- pkg/image/components.go
close https://github.com/goharbor/harbor-operator/issues/777
- minio/operator from `v4.0.6` to `v4.3.2`
- minio/minio from `RELEASE.2021-07-27T02-40-15Z` to `RELEASE.2021-10-27T16-29-42Z`
- minio/mc from `RELEASE.2021-03-23T05-46-11Z` to `RELEASE.2021-10-07T04-19-58Z`
> feat(mino) upgrade minio

- pkg/cluster/controllers/storage/ingress.go
close #793
allow add customize annotation for minio ingress
> fix minio annotation

- manifests/cluster/deployment.yaml
- pkg/controller/common.go
- pkg/controller/context.go
- pkg/controller/garbagecollector.go
- pkg/controller/internal/graph/graph.go
- pkg/factories/application/application.go
- pkg/graph/graph.go
- pkg/graph/types.go
- pkg/setup/setup.go
> feat: add garbagecollector

- apis/goharbor.io/v1beta1/harborcluster_webhook.go
> feat(harborcluster): don't allow users to switch type

- .github/kind_permission.yaml
- .github/workflows/tests.yml
- Makefile
- pkg/cluster/controllers/cache/resource_manager.go
close #814
add `OwnerReferencesPermissionEnforcement` in kind cluster, to simulate openshift cluster
> feat: enhance ci

- controllers/goharbor/harbor/ingresses.go
> fix(ingress): issue 823

- README.md
- docs/day2/day2-configurations.md
> doc(day2 config): remove day2 related content out

- charts/harbor-operator/README.md
- charts/harbor-operator/values.yaml
- go.mod
- go.sum
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/annotations.yaml
close https://github.com/goharbor/harbor-operator/issues/845
> bump up redis-operator v1.1.1

- README.md
- charts/harbor-operator/README.md
- charts/harbor-operator/values.yaml
- docs/installation/kustomization-custom.md
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- manifests/cluster/patch/annotations.yaml
> upgrade minio operator to v4.4.9

- config/samples/harborcluster-minimal/goharbor_v1alpha3_harbor.yaml
- docs/day2/day2-operations.md
- manifests/samples/full_stack.yaml
- manifests/samples/minimal_stack_fs.yaml
- manifests/samples/minimal_stack_incluster.yaml
- manifests/samples/standard_stack.yaml
- manifests/samples/standard_stack_fs.yaml
close https://github.com/goharbor/harbor-operator/issues/848
> use harbor v2.4.1 as default sample

- charts/harbor-operator/Chart.lock
- charts/harbor-operator/Chart.yaml
Signed-off-by: yxxhero <aiopsclub@163.com>
> fix typo in chart.yaml

- docs/day2/day2-configurations.md
Fixes: https://github.com/goharbor/harbor-operator/issues/867
> docs: fix day2 configuration sample cr

- docs/day2/day2-configurations.md
> [cherry-pick] docs: fix day2 configuration sample cr

- charts/harbor-operator/Chart.lock
- charts/harbor-operator/Chart.yaml
- charts/harbor-operator/README.md
- charts/harbor-operator/values.yaml
> update minio-operator 4.4.9

- controllers/goharbor/registry/deployments.go
> fix: registry deployment debug port should match the spec

- apis/meta/v1alpha1/logs.go
- charts/harbor-operator/templates/crds.yaml
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> Fix registry log enum

- Makefile
Signed-off-by: yxxhero <aiopsclub@163.com>
fix kubebuilder download url
> fix kubebuilder download url

- Makefile
ref: https://github.com/kubernetes-sigs/kind/issues/2765
> tools(kind): upgrade kind

- pkg/controller/apply.go
- pkg/controller/common.go
- pkg/controller/resource.go
Fixes: #825
Fixes: #824
Fixes: #743
> fix(controller): use update instead of patch

- config/samples/harborcluster-minimal/goharbor_v1alpha3_harbor.yaml
- go.mod
- go.sum
- manifests/samples/full_stack.yaml
- manifests/samples/minimal_stack_fs.yaml
- manifests/samples/minimal_stack_incluster.yaml
- manifests/samples/standard_stack.yaml
- manifests/samples/standard_stack_fs.yaml
> feat: bump up harbor to 2.5.1

- Makefile
- docs/installation/customize-storage-db-redis.md
Signed-off-by: yxxhero <aiopsclub@163.com>
update pgsql version
> update pgsql version

- apis/goharbor.io/v1beta1/harbor_types.go
- apis/goharbor.io/v1beta1/trivy_types.go
- charts/harbor-operator/templates/crds.yaml
- controllers/goharbor/harbor/manifests/trivy/default-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/expose-core-with-tls-expected.yaml
- controllers/goharbor/harbor/manifests/trivy/github-token-expected.yaml
- controllers/goharbor/harbor/trivy.go
- controllers/goharbor/trivy/configs.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
> Support offline scan option in trivy

- README.md
- charts/harbor-operator/Chart.lock
- charts/harbor-operator/Chart.yaml
- docs/LCM/upgrade-cluster.md
- docs/installation/by-helm-chart.md
- docs/installation/enable_minio_console.md
- docs/installation/kustomization-all-in-one.md
- docs/installation/kustomization-custom.md
- docs/makefile.md
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
close https://github.com/goharbor/harbor-operator/issues/911
> Update dependency minio 4.4.22

- docs/installation/customize-storage-db-redis.md
1. `the-psql-password` base64 encode should be `dGhlLXBzcWwtcGFzc3dvcmQ=` not `dGhlLXBzcWwtcGFzc3dvcmQK`
2. new bitnami/postgresql admin password config string is `auth.postgresPassword`
> fixed: postgresql password error

- controllers/goharbor/harbor/registryctl.go
- controllers/goharbor/registry/registryctl.go
- controllers/goharbor/registry/resources.go
- pkg/controller/resource.go
> [Cherry pick]fix: Ignore the status check for the registryctl cr in harbor controller

- docs/tutorial.md
> doc(tutorial): add warnings for ingress class

- Makefile
- apis/meta/v1alpha1/component.go
- charts/harbor-operator/templates/crds.yaml
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
issue: https://github.com/goharbor/harbor-operator/issues/928
upgrade controller gen version from `0.6.2` to `0.9.2`.
Signed-off-by: rongfu.leng <1275177125@qq.com>
> feat upgrade controller gen version

- apis/goharbor.io/v1beta1/harbor_types.go
- charts/harbor-operator/templates/crds.yaml
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
ref: https://github.com/goharbor/harbor-operator/issues/945
Signed-off-by: rongfu.leng <1275177125@qq.com>
> fix: tokenIssuer_field is not omitempty

- charts/harbor-operator/README.md
- charts/harbor-operator/values.yaml
- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
fix https://github.com/goharbor/harbor-operator/issues/961
> bump up redis-operator 1.2.0

- pkg/cluster/controllers/database/generate.go
This pull request is response to this issue: #978
> Update hba values for Postgres authentication

- manifests/cluster/deployment.yaml
- manifests/cluster/kustomization.yaml
- pkg/image/components.go
- pkg/image/image_test.go
Updated version and tag of Spilo as requested in #977
> Update Spilo version and tag

- MAINTAINERS
Everyone please vote bellow!
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
> Promote MarcelMue as Maintainer

- .github/auto-assignees.yaml
Signed-off-by: Marcel Mueller <marcel@giantswarm.io>
> Add MarcelMue to reviewers list

- .dockerignore
- .github/workflows/build-dev.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Dockerfile
- Makefile
- go.mod
- go.sum
issue https://github.com/goharbor/harbor-operator/issues/993
> add arm image

- go.mod
- go.sum
> chore: bump up github.com/goharbor/go-client v0.26.2

- .github/auto-assignees.yaml
- MAINTAINERS
Add Yan Wang to the maintainers list.
> docs: add yanwang to the maintainers list

- .github/workflows/build-dev.yml
- .github/workflows/chart-tests.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contour-tests.yml
- .github/workflows/harbor-e2e-tests.yml
- .github/workflows/tests.yml
Update the actions rule pattern from master to main.
> chore: update the github actions

- Makefile
- README.md
- apis/goharbor.io/v1alpha3/core_types.go
- apis/goharbor.io/v1beta1/core_types.go
- charts/harbor-operator/templates/NOTES.txt
- config/config/assets/jobservice-config.yaml.tmpl
- controllers/goharbor/core/deployments.go
- controllers/goharbor/harbor/registry.go
- controllers/goharbor/jobservice/deployments.go
- docs/development.md
- docs/installation/by-helm-chart.md
- docs/installation/kustomization-all-in-one.md
- docs/installation/kustomization-custom.md
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
Update the branch name from master to main for the documentations or code comments.
> docs: update the branch name master to main in the docs

- apis/meta/v1alpha1/component.go
- apis/meta/v1alpha1/zz_generated.deepcopy.go
- manifests/cluster/deployment.yaml
- manifests/harbor/deployment.yaml
This change allow user to inject
customized label to deployment.
> feat: customLabels in ComponentSpec
